### ISSUE TITLE
Win10 [go 1.6] fatal error: out of memory

### ISSUE THREAD

**Issue by CodyGuo** [visualfc/goqt#26]
D:\go\gopath\src\github.com\visualfc\goqt\examples\minimal>go build
fatal error: out of memory

runtime stack:
runtime.throw(0x7b4470, 0xd)
        c:/go/src/runtime/panic.go:530 +0x7f
runtime.(*mcache).refill(0xf60000, 0xe, 0x6695be6c)
        c:/go/src/runtime/mcache.go:121 +0xce
runtime.mallocgc.func2()
        c:/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x11382000)
        c:/go/src/runtime/asm_386.s:313 +0x5e
runtime.mstart()
        c:/go/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:267 fp=0x48d2571c sp=0x48d25718
runtime.mallocgc(0xd0, 0x78c140, 0x0, 0xbe11373)
        c:/go/src/runtime/malloc.go:643 +0x6ca fp=0x48d25788 sp=0x48d2571c
runtime.newobject(0x78c140, 0x0)
        c:/go/src/runtime/malloc.go:781 +0x41 fp=0x48d2579c sp=0x48d25788
cmd/compile/internal/gc.Prog(0x3, 0x6695c880)
        c:/go/src/cmd/compile/internal/gc/gsubr.go:113 +0x27f fp=0x48d257d0 sp=0x48d2579c
cmd/compile/internal/x86.gins(0x3, 0x0, 0x0, 0x0)
        c:/go/src/cmd/compile/internal/x86/gsubr.go:1790 +0x243 fp=0x48d25840 sp=0x48d257d0
cmd/compile/internal/gc.dsymptr(0x1ccd5540, 0x1010, 0x660aa000, 0x0, 0x1010)
        c:/go/src/cmd/compile/internal/gc/obj.go:339 +0x73 fp=0x48d258e4 sp=0x48d25840
cmd/compile/internal/gc.dextratype(0x1ccd5540, 0x28, 0x66079d40, 0x1c, 0x28)
        c:/go/src/cmd/compile/internal/gc/reflect.go:529 +0x379 fp=0x48d25934 sp=0x48d258e4
cmd/compile/internal/gc.dtypesym(0x66079d40, 0x66079d40)
        c:/go/src/cmd/compile/internal/gc/reflect.go:1197 +0x303 fp=0x48d25a08 sp=0x48d25934
cmd/compile/internal/gc.dcommontype(0x1ccd52c0, 0x0, 0x179f4000, 0x0)
        c:/go/src/cmd/compile/internal/gc/reflect.go:707 +0x741 fp=0x48d25ac8 sp=0x48d25a08
cmd/compile/internal/gc.dtypesym(0x179f4000, 0x203c3380)
        c:/go/src/cmd/compile/internal/gc/reflect.go:1167 +0xb28 fp=0x48d25b9c sp=0x48d25ac8
cmd/compile/internal/gc.dumptypestructs()
        c:/go/src/cmd/compile/internal/gc/reflect.go:1250 +0x40f fp=0x48d25bfc sp=0x48d25b9c
cmd/compile/internal/gc.dumpobj()
        c:/go/src/cmd/compile/internal/gc/obj.go:76 +0xb6c fp=0x48d25d24 sp=0x48d25bfc
cmd/compile/internal/gc.Main()
        c:/go/src/cmd/compile/internal/gc/lex.go:495 +0x1ce0 fp=0x48d25eb8 sp=0x48d25d24
cmd/compile/internal/x86.Main()
        c:/go/src/cmd/compile/internal/x86/galign.go:108 +0x53e fp=0x48d25f24 sp=0x48d25eb8
main.main()
        c:/go/src/cmd/compile/main.go:30 +0x117 fp=0x48d25f90 sp=0x48d25f24
runtime.main()
        c:/go/src/runtime/proc.go:188 +0x234 fp=0x48d25fb8 sp=0x48d25f90
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1585 +0x1 fp=0x48d25fbc sp=0x48d25fb8

D:\go\gopath\src\github.com\visualfc\goqt\examples\minimal>go version
go version go1.6 windows/386

D:\go\gopath\src\github.com\visualfc\goqt\examples\minimal>go env
set GOARCH=386
set GOBIN=D:\go\bin
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\go\gopath;D:\go\cpath
set GORACE=
set GOROOT=D:\go
set GOTOOLDIR=D:\go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by LER0ever** [comment]
same here !
Windows 10 64bit  
go 1.6 386
Out of memory！
