### ISSUE TITLE
go install get error:"fatal error: runtime: cannot map pages in arena address space"

### ISSUE THREAD

**Issue by SuperGod** [visualfc/goqt#6]
go install get error:"fatal error: runtime: cannot map pages in arena address space"

system : Windows 10 x86_64
go version:  go1.5.1 windows/386
Qt version: Qt 5.5.1, download from qt.io,build with mingw

**Comment by visualfc** [comment]
build and install goqt/ui request 2.5G memory

**Comment by llxwj** [comment]
```
D:\workspace\golang\src\github.com\visualfc\goqt\ui>go install -v
github.com/visualfc/goqt/ui
# github.com/visualfc/goqt/ui
fatal error: runtime: failed to release pages

runtime stack:
runtime.throw(0x7a44c0, 0x20)
        c:/go/src/runtime/panic.go:527 +0x7f
runtime.sysFree(0x0, 0x10000000, 0xdfd24)
        c:/go/src/runtime/mem_windows.go:86 +0x5b
runtime.mHeap_SysAlloc(0xb23640, 0x100000, 0x0)
        c:/go/src/runtime/malloc.go:418 +0x4a1
runtime.mHeap_Grow(0xb23640, 0x8, 0x0)
        c:/go/src/runtime/mheap.go:628 +0x52
runtime.mHeap_AllocSpanLocked(0xb23640, 0x1, 0x539c6624)
        c:/go/src/runtime/mheap.go:532 +0x574
runtime.mHeap_Alloc_m(0xb23640, 0x1, 0xe, 0x0, 0x539c6624)
        c:/go/src/runtime/mheap.go:425 +0x281
runtime.mHeap_Alloc.func1()
        c:/go/src/runtime/mheap.go:484 +0x3d
runtime.systemstack(0xdfe20)
        c:/go/src/runtime/asm_386.s:283 +0x81
runtime.mHeap_Alloc(0xb23640, 0x1, 0xe, 0x27f0100, 0x15a3)
        c:/go/src/runtime/mheap.go:485 +0x5a
runtime.mCentral_Grow(0xb288a0, 0x0)
        c:/go/src/runtime/mcentral.go:190 +0x8e
runtime.mCentral_CacheSpan(0xb288a0, 0x539c6624)
        c:/go/src/runtime/mcentral.go:86 +0x439
runtime.mCache_Refill(0x3006fc, 0xe, 0x539c6624)
        c:/go/src/runtime/mcache.go:118 +0xae
runtime.mallocgc.func2()
        c:/go/src/runtime/malloc.go:614 +0x2b
runtime.systemstack(0xb16b00)
        c:/go/src/runtime/asm_386.s:267 +0x57
runtime.mstart()
        c:/go/src/runtime/proc1.go:668

goroutine 1 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:222 fp=0x659fd608 sp=0x659fd604
runtime.mallocgc(0xd0, 0x760540, 0x0, 0x0)
        c:/go/src/runtime/malloc.go:615 +0x65a fp=0x659fd670 sp=0x659fd608
runtime.newobject(0x760540, 0x20903860)
        c:/go/src/runtime/malloc.go:763 +0x41 fp=0x659fd684 sp=0x659fd670
cmd/internal/obj/x86.doasm(0x1272c000, 0x20903860)
        c:/go/src/cmd/internal/obj/x86/asm6.go:3924 +0x13b1 fp=0x659fd8e4 sp=0x659fd684
cmd/internal/obj/x86.asmins(0x1272c000, 0x20903860)
        c:/go/src/cmd/internal/obj/x86/asm6.go:4320 +0xf74 fp=0x659fd9b4 sp=0x659fd8e4
cmd/internal/obj/x86.span6(0x1272c000, 0x22482120)
        c:/go/src/cmd/internal/obj/x86/asm6.go:1721 +0x923 fp=0x659fda9c sp=0x659fd9b4
cmd/internal/obj.Writeobjdirect(0x1272c000, 0x34d1bbb0)
        c:/go/src/cmd/internal/obj/objfile.go:297 +0x317 fp=0x659fdbf0 sp=0x659fda9c
cmd/compile/internal/gc.dumpobj()
        c:/go/src/cmd/compile/internal/gc/obj.go:96 +0xccb fp=0x659fdd40 sp=0x659fdbf0
cmd/compile/internal/gc.Main()
        c:/go/src/cmd/compile/internal/gc/lex.go:492 +0x1a8d fp=0x659fdec0 sp=0x659fdd40
cmd/compile/internal/x86.Main()
        c:/go/src/cmd/compile/internal/x86/galign.go:108 +0x53e fp=0x659fdf2c sp=0x659fdec0
main.main()
        c:/go/src/cmd/compile/main.go:24 +0xb2 fp=0x659fdf98 sp=0x659fdf2c
runtime.main()
        c:/go/src/runtime/proc.go:111 +0x234 fp=0x659fdfc0 sp=0x659fdf98
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1662 +0x1 fp=0x659fdfc4 sp=0x659fdfc0

D:\workspace\golang\src\github.com\visualfc\goqt\ui>
```
**System: windows10 64bit DDR 8G go 1.5.2 32bit qt 4.8.6**

**Comment by SuperGod** [comment]
I think maybe alloc 2.5GB memory of i386 is to big

**Comment by visualfc** [comment]
please go to https://github.com/golang/go/issues/13903 and report bug message
